table cotacoes
	lineageTag: 8b87ef43-c56d-4222-9657-41c6d85c38e1

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			```
		lineageTag: dcaa757d-edf0-4d77-a219-124214903bac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total R$' = ```
			
			SUMX(
			    moedas,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			) 
			```
		lineageTag: df1aded1-d3c0-4ac6-b4d5-8893d0aee7c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		lineageTag: cdf6621c-27ef-4750-b1b1-7f3873820d3a
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column DataHora
		dataType: dateTime
		formatString: General Date
		lineageTag: 00a4931d-2c78-4f9e-bd3d-f0639a3199db
		summarizeBy: none
		sourceColumn: DataHora

		annotation SummarizationSetBy = Automatic

	column Cotacao
		dataType: double
		lineageTag: cfe2458a-d2ba-41c8-ac5f-d12714406030
		summarizeBy: sum
		sourceColumn: Cotacao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TipoBoletim
		dataType: string
		lineageTag: 84e350a3-722f-4dba-b01a-79fc0f009175
		summarizeBy: none
		sourceColumn: TipoBoletim

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7576c8c9-fb21-4ada-9240-b784a8a3c5ad
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition cotacoes = m
		mode: import
		queryGroup: Fatos
		source = getCotacoes(data_inicial, data_final)

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

