table moedas
	lineageTag: 8546028a-a698-40b8-9c34-dfc35814670c

	measure 'Cotação do dia' = AVERAGE(cotacoes[Cotacao])
		displayFolder: Medidas
		lineageTag: 5878325d-13b4-4fd1-a9cf-6f821816733f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		lineageTag: 033ee64d-40d9-426c-a973-fec23a022352
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: a4984414-1da2-4990-a0f4-4fd703883c0f
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Formato
		dataType: string
		lineageTag: b5c88324-2679-478d-8f6c-778a0ebd1d7a
		summarizeBy: none
		sourceColumn: Formato

		annotation SummarizationSetBy = Automatic

	partition moedas = m
		mode: import
		queryGroup: Dimensões
		source = ```
				let
				    source = Table.FromRows(
				        {
				            {"BRL", "Real brasileiro", "R$ #,##0.00;R$ #,##0.00;-"},
				            {"AUD", "Dólar australiano", "$ #,##0.00;$ #,##0.00;-"},
				            {"CAD", "Dólar canadense", "$ #,##0.00;$ #,##0.00;-"},
				            {"CHF", "Franco suíço", "Fr #,##0.00;Fr #,##0.00;-"},
				            {"DKK", "Coroa dinamarquesa", "kr #,##0.00;kr #,##0.00;-"},
				            {"EUR", "Euro", "€ #,##0.00;€ #,##0.00;-"},
				            {"GBP", "Libra Esterlina", "£ #,##0.00;£ #,##0.00;-"},
				            {"JPY", "Iene", "¥ #,##0;¥ #,##0;-"},
				            {"NOK", "Coroa norueguesa", "kr #,##0.00;kr #,##0.00;-"},
				            {"SEK", "Coroa sueca", "kr #,##0.00;kr #,##0.00;-"},
				            {"USD", "Dólar dos Estados Unidos", "$ #,##0.00;$ #,##0.00;-"}
				        },
				        {"Moeda", "Nome", "Formato"}
				    ),
				    
				    changedType = Table.TransformColumnTypes(
				        source,{
				            {"Moeda", type text}, 
				            {"Nome", type text}, 
				            {"Formato", type text}
				        }
				    )
				
				in
				    changedType
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

