table transacoes
	lineageTag: db698edd-1c1a-4e05-bd43-4f9f625f2e2e

	measure 'Valor Total' = SUM(transacoes[Total])
		displayFolder: Medidas
		lineageTag: f01cf455-c06d-4ef2-b6ac-bb13d6c7bcc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotação do dia' = AVERAGE(cotacoes[Cotacao])
		displayFolder: Medidas
		lineageTag: 5878325d-13b4-4fd1-a9cf-6f821816733f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: double
		displayFolder: Colunas
		lineageTag: 687062f6-1fe4-4277-852f-b378e8a9d80f
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: Long Date
		displayFolder: Colunas
		lineageTag: 9ad661e5-9eec-40aa-be1f-0722d7972d62
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Total
		dataType: double
		displayFolder: Colunas
		lineageTag: 5acf70e7-4fe5-4bd2-b33b-8e9b928c27ef
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 00b41ff5-0e08-4b5e-a7e2-bc0b695587d1
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	partition transacoes = m
		mode: import
		queryGroup: Fatos
		source = ```
				let
				    source = Excel.Workbook(
				        File.Contents(base_transacoes), 
				        true, 
				        null
				    ),
				    
				    transacoes_Table = source{[Item="transacoes",Kind="Table"]}[Data],
				    
				    datesRestricted = Table.SelectRows(
				        transacoes_Table, 
				        each [Data] >= data_inicial and [Data] <= data_final
				    )
				in
				    datesRestricted
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

